openapi: 3.0.3
info:
  title: Character Query Logging API
  version: 1.0.0
  description: API for syncing OCID logs to Google Sheets

paths:
  /api/sync-ocids:
    post:
      summary: Sync accumulated OCID logs to Google Sheets
      description: Manually trigger synchronization of in-memory OCID records to Google Sheets
      operationId: syncOcids
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Sync completed successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - syncedCount
                properties:
                  success:
                    type: boolean
                    example: true
                  syncedCount:
                    type: integer
                    example: 150
                  errors:
                    type: array
                    items:
                      type: string
                    example: []
        '500':
          description: Sync failed
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: 'Google Sheets API error'
                  syncedCount:
                    type: integer
                    example: 0
