openapi: 3.0.3
info:
  title: API Call Throttling Contract
  description: Contract for API call throttling behavior in development vs production environments
  version: 1.0.0
  contact:
    name: Development Team

servers:
  - url: https://open.api.nexon.com
    description: Nexon MapleStory OpenAPI

components:
  schemas:
    ApiCall:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: Target API endpoint
        method:
          type: string
          enum: [GET, POST, PUT, DELETE, PATCH]
        headers:
          type: object
          additionalProperties:
            type: string
        body:
          type: object
        delayApplied:
          type: boolean
          description: Whether throttling delay was applied
        delayDuration:
          type: integer
          minimum: 0
          description: Delay duration in milliseconds
      required:
        - url
        - method
        - delayApplied
        - delayDuration

  parameters:
    Environment:
      name: environment
      in: header
      description: Runtime environment (development/production)
      schema:
        type: string
        enum: [development, production]
      required: true

  responses:
    ThrottledRequest:
      description: Request processed with appropriate throttling
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiCall'

x-throttling-rules:
  development:
    rateLimit: 5 requests/second
    delay: 200ms minimum per request
  production:
    rateLimit: 500 requests/second
    delay: 0ms
