openapi: 3.0.3
info:
  title: Combat Power Leaderboard API
  version: 1.0.0
  description: API for fetching combat power leaderboard data with server-side caching

servers:
  - url: /api
    description: Next.js API routes

paths:
  /leaderboard:
    get:
      summary: Get combat power leaderboard
      description: |
        Retrieves combat power leaderboard data from Google Sheet.
        Returns sorted list of characters by combat power (descending).
        Character info is fetched from CharacterInfo cache sheet.
        Supports pagination for infinite scroll.
      operationId: getLeaderboard
      parameters:
        - name: offset
          in: query
          description: Starting position (0-based)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: limit
          in: query
          description: Maximum number of entries to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaderboardResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /cron/update-character-info:
    post:
      summary: Update character info cache
      description: |
        Background CRON job to update CharacterInfo cache.
        Fetches character details from Nexon API and stores in Google Sheet.
        Should be triggered by external CRON service every 6 hours.
      operationId: updateCharacterInfoCache
      security:
        - cronSecret: []
      responses:
        '200':
          description: Cache update completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CronUpdateResponse'
        '401':
          description: Unauthorized - invalid CRON_SECRET
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    cronSecret:
      type: apiKey
      in: header
      name: Authorization
      description: 'Bearer {CRON_SECRET}'

  schemas:
    LeaderboardResponse:
      type: object
      required:
        - entries
        - totalCount
        - hasMore
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/LeaderboardEntry'
        totalCount:
          type: integer
          description: Total number of entries in leaderboard
          example: 50
        hasMore:
          type: boolean
          description: Whether more entries are available
          example: true
        offset:
          type: integer
          description: Current offset
          example: 0
        limit:
          type: integer
          description: Number of entries returned
          example: 20

    LeaderboardEntry:
      type: object
      required:
        - rank
        - ocid
        - combat_power
        - updated_at
      properties:
        rank:
          type: integer
          description: Rank position (1-based)
          example: 1
        ocid:
          type: string
          description: Character unique identifier
          example: 'abc123def456'
        combat_power:
          type: integer
          description: Combat power value
          example: 150000000
        updated_at:
          type: string
          format: date-time
          description: Combat power last update timestamp
          example: '2025-12-06T10:30:00Z'
        character_name:
          type: string
          description: Character name (from cache)
          example: '角色名稱'
        character_level:
          type: integer
          description: Character level (from cache)
          example: 285
        character_image:
          type: string
          format: uri
          description: Character avatar URL (from cache)
          example: 'https://open.api.nexon.com/static/maplestory/...'
        world_name:
          type: string
          description: Server name (from cache)
          example: '艾麗亞'
        character_class:
          type: string
          description: Character class (from cache)
          example: '乾坤'

    CronUpdateResponse:
      type: object
      required:
        - success
        - updated
        - failed
      properties:
        success:
          type: boolean
          description: Whether the update completed successfully
          example: true
        updated:
          type: integer
          description: Number of characters updated
          example: 45
        failed:
          type: integer
          description: Number of characters that failed to update
          example: 2
        duration:
          type: number
          description: Update duration in seconds
          example: 15.5

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: 'Failed to fetch leaderboard data'
