openapi: 3.0.3
info:
  title: Nexon MapleStory API Contracts
  version: 1.0.0
  description: API contracts for character stats and equipment data

servers:
  - url: https://open.api.nexon.com/maplestorytw/v1
    description: Nexon MapleStory API

paths:
  /character/stat:
    get:
      summary: Get character stats
      parameters:
        - name: ocid
          in: query
          required: true
          schema:
            type: string
          description: Character OCID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    nullable: true
                  character_class:
                    type: string
                    example: '英雄'
                  final_stat:
                    type: array
                    items:
                      type: object
                      properties:
                        stat_name:
                          type: string
                          example: '戰鬥力'
                        stat_value:
                          type: string
                          example: '463821790'
                  remain_ap:
                    type: integer
                    example: 0

  /character/item-equipment:
    get:
      summary: Get character equipment
      parameters:
        - name: ocid
          in: query
          required: true
          schema:
            type: string
          description: Character OCID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  preset_no:
                    type: integer
                    example: 2
                  item_equipment:
                    type: array
                    items:
                      type: object
                      properties:
                        item_name:
                          type: string
                        item_icon:
                          type: string
                        item_equipment_part:
                          type: string
                        item_equipment_slot:
                          type: string
                  item_equipment_preset_1:
                    type: array
                    description: Preset 1 equipment
                  item_equipment_preset_2:
                    type: array
                    description: Preset 2 equipment
                  item_equipment_preset_3:
                    type: array
                    description: Preset 3 equipment
